In [1]:
import torch

x_data = [1., 2., 3.]
y_data = [2., 4., 6.]

w = torch.Tensor([1.0])
w.requires_grad = True
# w = torch.Tensor([1.0], requires_grad = True)

In [2]:
# 构建计算图
def forward(x):
    return x*w

def loss(x, y):
    y_pred = forward(x)
    return (y_pred - y)**2

In [3]:
print("prediction (before training)", 4, forward(4).item())


prediction (before training) 4 4.0


In [4]:
learning_rate = 0.01

for epoch in range(100):
    for x, y in zip(x_data, y_data):
        l = loss(x,y)
        l.backward()
        gradient = w.grad #注意Tensor直接运算会构建计算图
        print('\tgradient: ', x, y, gradient.item())
        w.data = w.data - learning_rate*gradient

        w.grad.zero_()
    
    print("progress: ", epoch, l.item())

print("prediction (after training)", 4, forward(4).item())

	gradient:  1.0 2.0 -2.0
	gradient:  2.0 4.0 -7.840000152587891
	gradient:  3.0 6.0 -16.228801727294922
progress:  0 7.315943717956543
	gradient:  1.0 2.0 -1.478623867034912
	gradient:  2.0 4.0 -5.796205520629883
	gradient:  3.0 6.0 -11.998146057128906
progress:  1 3.9987640380859375
	gradient:  1.0 2.0 -1.0931644439697266
	gradient:  2.0 4.0 -4.285204887390137
	gradient:  3.0 6.0 -8.870372772216797
progress:  2 2.1856532096862793
	gradient:  1.0 2.0 -0.8081896305084229
	gradient:  2.0 4.0 -3.1681032180786133
	gradient:  3.0 6.0 -6.557973861694336
progress:  3 1.1946394443511963
	gradient:  1.0 2.0 -0.5975041389465332
	gradient:  2.0 4.0 -2.3422164916992188
	gradient:  3.0 6.0 -4.848389625549316
progress:  4 0.6529689431190491
	gradient:  1.0 2.0 -0.4417421817779541
	gradient:  2.0 4.0 -1.7316293716430664
	gradient:  3.0 6.0 -3.58447265625
progress:  5 0.35690122842788696
	gradient:  1.0 2.0 -0.3265852928161621
	gradient:  2.0 4.0 -1.2802143096923828
	gradient:  3.0 6.0 -2.650045394897

In [11]:
print(w.data, type(w.data))
print(w, type(w))
print(w.item(), type(w.item()))
print(w.grad.data, type(w.grad.data))
print(w.grad, type(w.grad))

tensor([2.0000]) <class 'torch.Tensor'>
tensor([2.0000], requires_grad=True) <class 'torch.Tensor'>
1.9999996423721313 <class 'float'>
tensor([0.]) <class 'torch.Tensor'>
tensor([0.]) <class 'torch.Tensor'>
